require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"

-- 2023-10-01 
require "user.lsp.rust-analyzer"
require "user.lsp.rust-tools"

require "user.telescope"
-- require "user.gitsigns"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.nvim-tree"
require "user.bufferline"
-- require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.impatient"
require "user.indentline"
require "user.alpha"
-- require "user.whichkey"
require "user.autocommands"
